FROM python:3.12.6-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV MONGODB_URL=${MONGODB_URL}
ENV MONGODB_DB=${MONGODB_DB}
ENV AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
ENV AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
ENV DOCKER_USERNAME=${DOCKER_USERNAME}
ENV DOCKER_PASSWORD=${DOCKER_PASSWORD}
ENV DOCKER_REGISTRY=${DOCKER_REGISTRY}
ENV DOCKER_ACCESS_TOKEN=${DOCKER_ACCESS_TOKEN}
ENV ON_RENDER_API_KEY=${ON_RENDER_API_KEY}
ENV ON_RENDER_SERVICE_ID=${ON_RENDER_SERVICE_ID}

ENV PORT=${PORT}

# ENV AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
# ENV AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
# ENV AUTH0_METADATA_URL=${AUTH0_METADATA_URL}
# ENV AUTH0_DOMAIN=${AUTH0_DOMAIN}
# ENV AUTH0_AUTHORIZATION_URL=${AUTH0_AUTHORIZATION_URL}
# ENV AUTH0_ACCESS_TOKEN_URL=${AUTH0_ACCESS_TOKEN_URL}
# ENV AUTH0_REDIRECT_URL=${AUTH0_REDIRECT_URL}
# ENV AUTH0_API_IDENTIFIER=${AUTH0_API_IDENTIFIER}
# ENV AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
# ENV APP_SECRET_KEY=${APP_SECRET_KEY}
# ENV AUTH0_AUDIENCE=${AUTH0_AUDIENCE}

EXPOSE ${POR
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "${PORT}"]